#page title
page_title                                : "Auftakt"                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1517383962                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  /Auftakt/assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :  Auftakt                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :  Free                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : iOS Metronome with a pracice mode.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marc Rummel
your_link                                 : https://www.github.com/thestoneage/Auftakt
your_city                                 : Karlsruhe
email_address                             : thestoneagesoftware@gmail.com
facebook_username                         :
#instagram_username                       : ebaehr
twitter_username                          : thestoneage
github_username                           : thestoneage
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Metronome
    description                           : Metronome with multiple Measures, Subdivisions and Sounds.
    fontawesome_icon_name                 : magic

  - title                                 : Tap-Tempo
    description                           : Set BPMs by tapping on a button.
    fontawesome_icon_name                 : magic

  - title                                 : Practice Mode
    description                           : Practice musical pieces and increase your speed,
    fontawesome_icon_name                 : magic

  - title                                 : Multiple Sounds
    description                           : Select sounds that suit your preference.
    fontawesome_icon_name                 : sync

  - title                                 : No Adds no data collection
    description                           : No Adds in the app and no data collection.
    fontawesome_icon_name                 : adjust

  - title                                 : Presets
    description                           : Presets for metronome and practice mode.
    fontawesome_icon_name                 : magic

  - title                                 : Dark Mode
    description                           : Auftakt supports dark mode.
    fontawesome_icon_name                 : mobile
    
  - title                                 : Open Source
    description                           : You can check out the source code on github.
    fontawesome_icon_name                 : sync

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : /assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
